/**
 * 
 */
var booklist=[
	{no:1, name:'小学语文-一年级下册-统编版-教材电子课本',sp:4, ep:129, code:'cqgc'},
	{no:2, name:'课时学练测-语文-一年级下册-配人教版',sp:4, ep:63, code:'smrl'},
	{no:3, name:'小学语文-二年级下册-统编版-教材电子课本',sp:4, ep:129, code:'iypn'},
	{no:4, name:'课时学练测-语文-二年级下册-配人教版',sp:4, ep:63, code:'eczw'},
	{no:5, name:'小学语文-三年级下册-统编版-教材电子课本',sp:4, ep:129, code:'daqk'},
	{no:6, name:'课时学练测-语文-三年级下册-配人教版',sp:4, ep:63, code:'bbms'},
	{no:7, name:'小学语文-四年级下册-统编版-教材电子课本',sp:4, ep:129, code:'neay'},
	{no:8, name:'课时学练测-语文-四年级下册-配人教版',sp:4, ep:63, code:'hayo'},
	{no:9, name:'小学语文-五年级下册-统编版-教材电子课本',sp:4, ep:129, code:'mcsy'},
	{no:10, name:'课时学练测-语文-五年级下册-配人教版',sp:4, ep:63, code:'eejq'},
	{no:11, name:'小学语文-六年级下册-统编版-教材电子课本',sp:4, ep:129, code:'winp'},
	{no:12, name:'课时学练测-语文-六年级下册-配人教版',sp:4, ep:63, code:'xlde'},
	{no:13, name:'小学数学-一年级下册-人教版-教材电子课本',sp:4, ep:129, code:'qhpr'},
	{no:14, name:'课时学练测-数学-一年级下册-配人教版',sp:4, ep:63, code:'sccq'},
	{no:15, name:'小学数学-二年级下册-人教版-教材电子课本',sp:4, ep:129, code:'ayoe'},
	{no:16, name:'课时学练测-数学-二年级下册-配人教版',sp:4, ep:63, code:'nlwc'},
	{no:17, name:'小学数学-三年级下册-人教版-教材电子课本',sp:4, ep:129, code:'peep'},
	{no:18, name:'课时学练测-数学-三年级下册-配人教版',sp:4, ep:63, code:'psqc'},
	{no:19, name:'小学数学-四年级下册-人教版-教材电子课本',sp:4, ep:129, code:'mlpe'},
	{no:20, name:'课时学练测-数学-四年级下册-配人教版',sp:4, ep:63, code:'acbw'},
	{no:21, name:'小学数学-五年级下册-人教版-教材电子课本',sp:4, ep:129, code:'jjjz'},
	{no:22, name:'课时学练测-数学-五年级下册-配人教版',sp:4, ep:63, code:'uqvl'},
	{no:23, name:'小学数学-六年级下册-人教版-教材电子课本',sp:4, ep:129, code:'zkyh'},
	{no:24, name:'课时学练测-数学-六年级下册-配人教版',sp:4, ep:63, code:'lzig'},
	{no:25, name:'小学数学-一年级下册-北师大版-教材电子课本',sp:4, ep:129, code:'yrxy'},
	{no:26, name:'课时学练测-数学-一年级下册-配北师大版',sp:4, ep:63, code:'pbqn'},
	{no:27, name:'小学数学-二年级下册-北师大版-教材电子课本',sp:4, ep:129, code:'tefx'},
	{no:28, name:'课时学练测-数学-二年级下册-配北师大版',sp:4, ep:63, code:'oogx'},
	{no:29, name:'小学数学-三年级下册-北师大版-教材电子课本',sp:4, ep:129, code:'uilf'},
	{no:30, name:'课时学练测-数学-三年级下册-配北师大版',sp:4, ep:63, code:'omjj'},
	{no:31, name:'小学数学-四年级下册-北师大版-教材电子课本',sp:4, ep:129, code:'htbs'},
	{no:32, name:'课时学练测-数学-四年级下册-配北师大版',sp:4, ep:63, code:'lnci'},
	{no:33, name:'小学数学-五年级下册-北师大版-教材电子课本',sp:4, ep:129, code:'wdsg'},
	{no:34, name:'课时学练测-数学-五年级下册-配北师大版',sp:4, ep:63, code:'pdos'},
	{no:35, name:'小学数学-六年级下册-北师大版-教材电子课本',sp:4, ep:129, code:'ilzu'},
	{no:36, name:'课时学练测-数学-六年级下册-配北师大版',sp:4, ep:63, code:'ctxt'},
	{no:37, name:'小学英语-三年级下册-人教（PEP）版-教材电子课本',sp:4, ep:129, code:'moug'},
	{no:38, name:'课时学练测-英语-三年级下册-配人教（PEP）版',sp:4, ep:63, code:'vsoq'},
	{no:39, name:'小学英语-四年级下册-人教（PEP）版-教材电子课本',sp:4, ep:129, code:'lvou'},
	{no:40, name:'课时学练测-英语-四年级下册-配人教（PEP）版',sp:4, ep:63, code:'yicp'},
	{no:41, name:'小学英语-五年级下册-人教（PEP）版-教材电子课本',sp:4, ep:129, code:'cvdz'},
	{no:42, name:'课时学练测-英语-五年级下册-配人教（PEP）版',sp:4, ep:63, code:'yicw'},
	{no:43, name:'小学英语-六年级下册-人教（PEP）版-教材电子课本',sp:4, ep:129, code:'doij'},
	{no:44, name:'课时学练测-英语-六年级下册-配人教（PEP）版',sp:4, ep:63, code:'qrpo'}
];